#pragma once
#pragma comment (lib, "d3d10.lib")
#pragma comment (lib, "d3d10_1.lib")
#pragma comment (lib, "d3dx10.lib")
#pragma comment (lib, "d3dx10d.lib")
#pragma comment (lib, "dxgi.lib")
#pragma comment (lib, "dxguid.lib")
#pragma comment (lib, "d3dcompiler.lib")
#pragma comment (lib, "D3DCSX.lib")
#pragma comment (lib, "dxerr.lib")
#pragma comment (lib, "DXUT.lib")
#pragma comment (lib, "DXUTOpt.lib")